<a href="https://colab.research.google.com/github/peta-m175/rabbit_challenge/blob/master/deep_learning/day1/exercises/1_1_forward_propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 準備

## Googleドライブのマウント

In [41]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## sys.pathの設定

以下では，Googleドライブのマイドライブ直下にDNN_codeフォルダを置くことを仮定しています．必要に応じて，パスを変更してください．

In [42]:
import sys
sys.path.append('/content/drive/My Drive/rabbit_challenge/DNN_code_colab_ver200425')

# importと関数定義

In [43]:
import numpy as np
from common import functions
import matplotlib.pyplot as plt

#def print_vec(text, vec):
def print_vec(text, vec, print_shape=False):
    print("*** " + text + " ***")
    print(vec)
    if print_shape:
      print("shape: " + str(vec.shape))
    print("")


# 順伝播（単層・単ユニット）

In [44]:
# 順伝播（単層・単ユニット）

# 重み
W = np.array([[0.1], [0.2]])

## 試してみよう_配列の初期化
#W = np.zeros(2)
#W = np.ones(2)
#W = np.random.rand(2)
#W = np.random.randint(5, size=(2))

print_vec("重み", W)


# バイアス
b = 0.5

## 試してみよう_数値の初期化
#b = np.random.rand() # 0~1のランダム数値
#b = np.random.rand() * 10 -5  # -5~5のランダム数値

print_vec("バイアス", b)

# 入力値
x = np.array([2, 3])
print_vec("入力", x)


# 総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.relu(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1]
 [0.2]]

*** バイアス ***
0.5

*** 入力 ***
[2 3]

*** 総入力 ***
[1.3]

*** 中間層出力 ***
[1.3]



# 順伝播（単層・複数ユニット）


In [50]:
# 順伝播（単層・複数ユニット）

# 重み
W = np.array([
    [0.1, 0.2, 0.3], 
    [0.2, 0.3, 0.4], 
    [0.3, 0.4, 0.5],
    [0.4, 0.5, 0.6]
])
print_vec("重み", W)

## 試してみよう_配列の初期化
W = np.zeros((4,3))
print_vec("重み:np.zeros", W)
W = np.ones((4,3))
print_vec("重み:np.ones", W)
W = np.random.rand(4,3)
print_vec("重み:np.random.rand", W)
W = np.random.randint(5, size=(4,3))
print_vec("重み:np.random.randint", W)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)


#  総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1 0.2 0.3]
 [0.2 0.3 0.4]
 [0.3 0.4 0.5]
 [0.4 0.5 0.6]]

*** 重み:np.zeros ***
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

*** 重み:np.ones ***
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

*** 重み:np.random.rand ***
[[0.12821121 0.41627212 0.14882793]
 [0.55444988 0.53567332 0.62431314]
 [0.86243352 0.25897253 0.04602904]
 [0.49315969 0.27868807 0.48859153]]

*** 重み:np.random.randint ***
[[1 3 4]
 [0 0 4]
 [2 3 2]
 [4 0 0]]

*** バイアス ***
[0.1 0.2 0.3]

*** 入力 ***
[ 1.  5.  2. -1.]

*** 総入力 ***
[ 1.1  9.2 28.3]

*** 中間層出力 ***
[0.75026011 0.99989897 1.        ]



# 順伝播（3層・複数ユニット）

In [46]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    
    """
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W2'] = np.array([
        [0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]
    ])
    network['W3'] = np.array([
        [0.1, 0.3],
        [0.2, 0.4]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1, 0.2])
    network['b3'] = np.array([1, 2])
    """

    network['W1'] = np.random.rand(2,3)
    network['W2'] = np.random.rand(3,2)
    network['W3'] = np.random.rand(2,2)
    network['b1'] = np.random.rand(3)
    network['b2'] = np.random.rand(2)
    network['b3'] = np.random.randint(3,size=(2))

    print_vec("重み1", network['W1'], print_shape=True)
    print_vec("重み2", network['W2'], print_shape=True)
    print_vec("重み3", network['W3'], print_shape=True)
    print_vec("バイアス1", network['b1'], print_shape=True)
    print_vec("バイアス2", network['b2'], print_shape=True)
    print_vec("バイアス3", network['b3'], print_shape=True)

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", z1)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1, z2

# 入力値
x = np.array([1., 2.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

*** 入力 ***
[1. 2.]

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.44278913 0.06242304 0.87729236]
 [0.79277088 0.11357023 0.41661977]]
shape: (2, 3)

*** 重み2 ***
[[0.73969221 0.16369885]
 [0.15251205 0.92794803]
 [0.0011344  0.84296966]]
shape: (3, 2)

*** 重み3 ***
[[0.71695713 0.14961028]
 [0.12308888 0.53854488]]
shape: (2, 2)

*** バイアス1 ***
[0.64089373 0.17323652 0.29955499]
shape: (3,)

*** バイアス2 ***
[0.50277833 0.46054077]
shape: (2,)

*** バイアス3 ***
[2 1]
shape: (2,)

##### 順伝播開始 #####
*** 総入力1 ***
[2.66922462 0.46280003 2.01008688]

*** 中間層出力1 ***
[2.66922462 0.46280003 2.01008688]

*** 総入力2 ***
[2.55004579 3.02138641]

*** 出力1 ***
[2.66922462 0.46280003 2.01008688]

出力合計: 5.142111530810167


# 多クラス分類（2-3-4ネットワーク）

In [47]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    """
    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W2'] = np.array([
        [0.1, 0.4, 0.7, 1.0],
        [0.2, 0.5, 0.8, 1.1],
        [0.3, 0.6, 0.9, 1.2]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1, 0.2, 0.3, 0.4])
    """

    network['W1'] = np.random.rand(3,5)
    network['W2'] = np.random.rand(5,4)
    network['b1'] = np.random.rand(5)
    network['b2'] = np.random.rand(4)

    print_vec("重み1", network['W1'], print_shape=True )
    print_vec("重み2", network['W2'], print_shape=True )
    print_vec("バイアス1", network['b1'], print_shape=True)
    print_vec("バイアス2", network['b2'], print_shape=True)

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
#x = np.array([1., 2.])
x = np.array([1., 2., 3.])

# 目標出力
#d = np.array([0, 0, 0, 1])
d = np.array([0, 0, 0, 1, 0])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[0.01621722 0.84034712 0.10039044 0.74503117 0.68283422]
 [0.69195635 0.70745101 0.16990678 0.87657798 0.07127271]
 [0.72221437 0.80276661 0.11962835 0.96166115 0.79733358]]
shape: (3, 5)

*** 重み2 ***
[[0.83969372 0.4324945  0.12455701 0.65365165]
 [0.64985458 0.10969922 0.54659451 0.2916616 ]
 [0.59627653 0.27555116 0.63041954 0.3289409 ]
 [0.52573302 0.12666914 0.54399239 0.42960243]
 [0.39017414 0.96817008 0.77256118 0.33903983]]
shape: (5, 4)

*** バイアス1 ***
[0.2462972  0.24238565 0.69159712 0.61744691 0.01904137]
shape: (5,)

*** バイアス2 ***
[0.37114676 0.93242507 0.31738593 0.43909725]
shape: (4,)

##### 順伝播開始 #####
*** 総入力1 ***
[3.81307024 4.90593463 1.49068616 6.00061749 3.23642175]

*** 中間層出力1 ***
[3.81307024 4.90593463 1.49068616 6.00061749 3.23642175]

*** 総入力2 ***
[12.06745396  7.42399422 10.17826926  8.52789307]

*** 出力1 ***
[0.84044529 0.00808873 0.12707115 0.02439482]

出力合計: 0.9999999999999999

##### 結果表示 #####
*** 出力 ***
[0.84044529 0.00

# 回帰（2-3-2ネットワーク）

In [48]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    """
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W2'] = np.array([
        [0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1, 0.2])
    """

    network['W1'] = np.random.rand(3,5)
    network['W2'] = np.random.rand(5,4)
    network['b1'] = np.random.rand(5)
    network['b2'] = np.random.rand(4)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))
    
    return y, z1

# 入力値
#x = np.array([1., 2.])
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4., 3., 1.])
# 誤差
loss = functions.mean_squared_error(d, y)
## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[0.32503559 0.8286645  0.09931416 0.50385225 0.8252113 ]
 [0.7528989  0.0057881  0.86015703 0.61042787 0.30403463]
 [0.84115971 0.7024655  0.74808258 0.3500353  0.34648239]]

*** 重み2 ***
[[0.82928208 0.1044725  0.64930234 0.29254832]
 [0.89718577 0.026718   0.85377424 0.24700399]
 [0.59510588 0.69253745 0.50289734 0.6616324 ]
 [0.20586665 0.33206087 0.5162839  0.24347878]
 [0.47597758 0.837421   0.25746329 0.60987527]]

*** バイアス1 ***
[0.7493871  0.6610911  0.69621588 0.37006393 0.33545794]

*** バイアス2 ***
[0.93186923 0.07768597 0.6128156  0.58882101]

##### 順伝播開始 #####
*** 総入力1 ***
[5.10369962 3.60872831 4.76009186 3.1448778  2.80818566]

*** 中間層出力1 ***
[5.10369962 3.60872831 4.76009186 3.1448778  2.80818566]

*** 総入力2 ***
[13.21879307  7.39976661 11.74819099  8.60105509]

*** 出力1 ***
[13.21879307  7.39976661 11.74819099  8.60105509]

出力合計: 19.425583258769443

##### 結果表示 #####
*** 中間層出力 ***
[5.10369962 3.60872831 4.76009186 3.1448778  2.80818566]

***

# 2値分類（2-3-1ネットワーク）

In [49]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    """
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W2'] = np.array([
        [0.2],
        [0.4],
        [0.6]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1])
    """
    network['W1'] = np.random.rand(5,10)
    network['W2'] = np.random.rand(10,1)
    network['b1'] = np.random.rand(10)
    network['b2'] = np.random.rand(1)
    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']    

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = functions.sigmoid(u2)
            
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1


# 入力値
#x = np.array([1., 2.])
x = np.array([1., 2., 3., 4., 5.])
# 目標出力
d = np.array([3])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[ 8.1954869   5.58022803  9.70075611  5.31832661  7.55673194  4.59941891
  8.99409643  7.32257932  9.16868921 12.11996104]

*** 中間層出力1 ***
[ 8.1954869   5.58022803  9.70075611  5.31832661  7.55673194  4.59941891
  8.99409643  7.32257932  9.16868921 12.11996104]

*** 総入力2 ***
[44.96789371]

*** 出力1 ***
[1.]

出力合計: 78.55627451685008

##### 結果表示 #####
*** 中間層出力 ***
[ 8.1954869   5.58022803  9.70075611  5.31832661  7.55673194  4.59941891
  8.99409643  7.32257932  9.16868921 12.11996104]

*** 出力 ***
[1.]

*** 訓練データ ***
[3]

*** 誤差 ***
-9.999999505838704e-08

